name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Install Dependencies
      working-directory: Zomato.Web/app
      run: npm ci
    - name: Build with angular
      working-directory: Zomato.Web/app
      run: npm run build-prod
    - name: Build with dotnet
      run: dotnet build
    - name: Install elastic beanstalk with dotnet
      run: dotnet tool install -g Amazon.ElasticBeanstalk.Tools
    - name: Publish with dotnet to AWS ElasticBeanstalk
      working-directory: Zomato.Web
      run: dotnet-eb deploy-environment
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.aws_access_key}}
        AWS_SECRET_KEY: ${{secrets.aws_secret_key}}
