name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with angular
      working-directory: Zomato.Web/app
      run: ng build --prod --output-hashing=none
    - name: Build with dotnet
      run: dotnet build
    - name: Publish with dotnet
      run: dotnet publish 
