name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Install Dependencies
      run: cd Zomato.Web/app && npm install
    - name: Build with dotnet
      run: dotnet build --configuration Release
